### ISSUE TITLE
Question on aseg

### ISSUE THREAD

**Issue by ajdneuro** [DCAN-Labs/dcan-infant-pipeline#6]
Hello,

Thank you for sharing this pipeline! I am just looking at T1 and T2, I wondering in which output folder is the final 'aseg' to calculate subcortical volumes from? Thanks,
Alex

**Comment by LuciMoore** [comment]
Hi, Alex

It should be `aseg_acpc.nii.gz` under `sub-<>/ses-<>/files/T1w` in the outputs. There is also a FreeSurfer stats file that I believe should contain this information - `files/T1w/subID/stats/aseg.stats`
